/**
 * UI components barrel export.
 *
 * This file re-exports all components from @realtime/ui (enterprise component library)
 * and any app-specific UI components that haven't been moved yet.
 *
 * Components can be imported as: import { Button, Input } from '@/shared/ui';
 */

// Re-export all from @realtime/ui
export {
  // Base components
  Button,
  buttonVariants,
  type ButtonProps,
  Input,
  type InputProps,
  Card,
  CardHeader,
  CardFooter,
  CardTitle,
  CardDescription,
  CardContent,
  CardStripe,
  CardAccent,
  CardCorner,
  cardVariants,
  getStaggerDelay,
  STAGGER_DELAYS,
  type CardProps,
  type CardStripeProps,
  type CardAccentProps,
  type StatusGradient,
  Label,
  Badge,
  badgeVariants,
  type BadgeProps,
  Avatar,
  AvatarImage,
  AvatarFallback,
  UserAvatar,
  Skeleton,
  Checkbox,
  Switch,
  Textarea,
  type TextareaProps,
  Slider,
  RadioGroup,
  RadioGroupItem,
  Progress,
  Separator,
  Alert,
  AlertTitle,
  AlertDescription,
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableHead,
  TableRow,
  TableCell,
  TableCaption,
  Command,
  CommandDialog,
  CommandInput,
  CommandList,
  CommandEmpty,
  CommandGroup,
  CommandItem,
  CommandShortcut,
  CommandSeparator,

  // Primitives
  Dialog,
  DialogPortal,
  DialogOverlay,
  DialogTrigger,
  DialogClose,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogTitle,
  DialogDescription,
  Popover,
  PopoverTrigger,
  PopoverContent,
  PopoverAnchor,
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuCheckboxItem,
  DropdownMenuRadioItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuGroup,
  DropdownMenuPortal,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuRadioGroup,
  Tooltip,
  TooltipTrigger,
  TooltipContent,
  TooltipProvider,
  Select,
  SelectGroup,
  SelectValue,
  SelectTrigger,
  SelectContent,
  SelectLabel,
  SelectItem,
  SelectSeparator,
  SelectScrollUpButton,
  SelectScrollDownButton,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent,
  AlertDialog,
  AlertDialogPortal,
  AlertDialogOverlay,
  AlertDialogTrigger,
  AlertDialogContent,
  AlertDialogHeader,
  AlertDialogFooter,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogAction,
  AlertDialogCancel,
  ScrollArea,
  ScrollBar,
  Slot,
  Slottable,

  // Themes
  colorTokens,
  radiusTokens,
  shadowTokens,
  zIndexTokens,

  // Hooks
  useClipboard,
  useDebounce,
  useDebouncedCallback,
  useLocalStorage,
  useMediaQuery,
  useBreakpoint,
  usePrefersReducedMotion,
  usePrefersDarkMode,

  // Utility
  cn,
} from '@realtime/ui';

// App-specific components that need to stay in apps/web
// (these have dependencies on app context or business logic)

// Sheet (Mobile Sidebar) - uses app-specific styling
export {
  Sheet,
  SheetPortal,
  SheetOverlay,
  SheetTrigger,
  SheetClose,
  SheetContent,
  SheetHeader,
  SheetFooter,
  SheetTitle,
  SheetDescription,
} from './sheet';

// Sonner (Toast) - configured with app theme
export { Toaster } from './sonner';

// DataTable - re-exported from @realtime/ui (new implementation)
export {
  // Main components
  DataTable,
  BaseTable,
  // Parts
  TableEmptyState,
  LoadingState,
  RowActionsMenu,
  SortableHeader,
  TableToolbar,
  TablePagination,
  // Types
  type TableColumn,
  type RowAction,
  type FilterConfig,
  type FilterOption,
  type SortState,
  type FilterState,
  type PaginationState,
  type RowSelectionState,
  type TableDensity,
  type DataTableProps,
  type BaseTableProps,
  type TableEmptyStateProps,
  type LoadingStateProps,
  type RowActionsMenuProps,
  type SortableHeaderProps,
  type TableToolbarProps,
  type TablePaginationProps,
  // Variants
  tableContainerVariants,
  tableRowVariants,
  tableCellVariants,
  tableHeadVariants,
  cellContentVariants,
  // Form Field
  FormField,
  FormFieldLabel,
  FormFieldDescription,
  FormFieldError,
  FormFieldControl,
  Form,
  type FormFieldProps,
  type FormFieldLabelProps,
  type FormFieldDescriptionProps,
  type FormFieldErrorProps,
  type FormFieldControlProps,
  // Date Picker
  Calendar,
  DatePicker,
  DateRangePicker,
  TimeInput,
  type CalendarProps,
  type DateRange,
  type DatePickerProps,
  type DateRangePickerProps,
  type TimeInputProps,
  // Combobox
  Combobox,
  type ComboboxProps,
  type ComboboxOption,
  // CopyButton
  CopyButton,
  type CopyButtonProps,
  // FileUpload
  FileUpload,
  type FileUploadProps,
  type UploadedFile,
  // EmptyState
  EmptyState,
  type EmptyStateProps,
  // PageHeader
  PageHeader,
  Breadcrumbs,
  type PageHeaderProps,
  type BreadcrumbsProps,
  type BreadcrumbItem,
  // Timeline
  Timeline,
  TimelineItem,
  type TimelineProps,
  type TimelineItemProps,
  // MetricCard
  MetricCard,
  Sparkline,
  type MetricCardProps,
  type SparklineProps,
  // AppShell
  AppShell,
  AppShellProvider,
  useAppShell,
  AppShellHeader,
  AppShellSidebar,
  AppShellContent,
  type AppShellProps,
  type AppShellContextValue,
  type AppShellProviderProps,
  type AppShellHeaderProps,
  type AppShellSidebarProps,
  type AppShellContentProps,
} from '@realtime/ui';
